config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  resources :weeks do
    resources :days do 
      resources :notes
    end
  end

  resources :days
  resources :notes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
    has_many :notes
    belongs_to :week
    after_create :set_title


    def self.today
        self.where("date = ?", "#{Date.today}")
    end

    def set_title
        self.title = self.date.strftime('%A')
        self.save
    end

    
end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :day

    
end

app/models/week.rb
class Week < ApplicationRecord
    validates_presence_of :start_day
    validates_uniqueness_of :start_day, :message => "already exists."
    has_many :days
    after_create :add_days

    def add_days
        self.days.create(date: "#{self.start_day}")
        self.days.create(date: "#{self.start_day + 1}")
        self.days.create(date: "#{self.start_day + 2}")
        self.days.create(date: "#{self.start_day + 3}")
        self.days.create(date: "#{self.start_day + 4}")
        self.days.create(date: "#{self.start_day + 5}")
        self.days.create(date: "#{self.start_day + 6}")
    end

    def current_week
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def index
        if !Day.all.empty?
            @today = Day.today.last
            @week = @today.week
            render '/index'
        else
            @today = Day.new
            @week = Week.new
            render '/index'
        end
    end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
    before_action :set_days
    before_action :set_week

    def index
    end

    def new
        @day = Day.new
    end

    def create
        @day = Day.create!(day_params)
    end

    def show
        @day = Day.find(params[:id])
        render json: @day
    end

    def edit
    end

    def update
    end

    def destroy
    end


    private

    def set_days
        @days = Day.all
    end

    def set_day
        @day = Day.find(params[:id])
    end

    def set_week
        @week = Week.find(params[:week_id])
    end

    def day_params
        params.require(:day).permit(
            :title,
            :id,
            :week_id
        )
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    def index
    end

    def new
        @note = Note.new
    end

    def create
    end

    def show
    end

    def edit
    end

    def update
    end

    def destroy
    end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
    before_action :set_weeks
    before_action :set_week, only: [:show, :update]

    def index
        @week = Week.new
    end
    
    def new
        @week = Week.new
    end

    def create
        @week = Week.create(week_params)
        if @week.save
            respond_to do |f|

                f.html { redirect_to weeks_path }
                f.json { render :json => @week }

            end
        else
            render new_week_path
        end
    end

    def show
        @week = Week.find(params[:id])
        respond_to do |f|
            f.json {render :json => @week}
            f.html {}
        end
    end

    def update
    end

    private

    def set_weeks
        @weeks = Week.all
    end

    def set_week
        @week = Week.find(params[:id])
    end

    def week_params
        params.require(:week).permit(
            :id,
            :start_day
        )
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/days/index.html.erb
<%= link_to "Add a Day ", new_day_path %>
<% @week.days.each do |d| %>
<%= d.title %>
<%= d.date %>
<% end %>

app/views/days/new.html.erb
<%= form_for @day do |d| %>
<%= d.label :title %>
<%= d.text_field :title %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Goat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div class="nav_button"><%= link_to "Weeks", weeks_path %></div>
      <div class="nav_button"><%= link_to "Home", root_path %></div>
      <div class="nav_button"><%#= link_to "Notes", notes_path %></div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/weeks/index.html.erb
<div>
<%= form_for @week do |nw| %>
    <% if @week.errors.any? %>
        <% @week.errors.full_messages.each do |message| %>
            <%= message %>
        <% end %>
    <% end %>
    <%= nw.label :start_day %>
    <%= nw.date_field :start_day %>
    <%= nw.submit %>
<% end %>
</div>

<div>
    <% @weeks.each do |w| %>
        <div class="dates">
            <%= link_to "#{w.start_day}", week_path(w), :class => "date_link"  %>
        </div>
        <div id='week_info_<%= w.id%>'>
        </div>
        <%= link_to 'Go to Week', week_path(w) %>
    <% end %>
    <div id="ajax_links">
    </div>
</div>

<div>

app/views/weeks/new.html.erb
<%= form_for @week do |nw| %>
    <% if @week.errors.any? %>
        <% @week.errors.full_messages.each do |message| %>
            <%= message %>
        <% end %>
    <% end %>
    <%= nw.label :start_day %>
    <%= nw.date_field :start_day %>
    <%= nw.submit %>
<% end %>

app/views/weeks/show.html.erb
<div class="weekday">
    <% @day = @week.days.first %>
    <div class="day_title">
    <%= @day.title %>
    </div>
    <div class="day_date">
    <%= @day.date %>
    </div>
    <div class="day_notes">
    <% @day.notes.each do |n| %>
        <%= n.content %>
    <% end %>
    </div>
    <%= link_to '>', week_path(@week), :class => "week_path" %>
</div>